### ISSUE TITLE
Support Fisher installation

### ISSUE THREAD

**Issue by andreiborisov** [qiuxiang/flutter-fish-completions#2]
Thank you for this project! 🙌

It would be convenient if we could install the completions via [Fisher](https://github.com/jorgebucaran/fisher) instead of downloading a release. This way we can configure it locally to auto-update, save it in dotfiles, etc.

**Comment by qiuxiang** [comment]
try `fisher install qiuxiang/flutter-fish-completions`

**Comment by andreiborisov** [comment]
Works like a charm! Thank you🚀
